// src/bootstrap.js
//
// Runs once, the first time Helm starts (or whenever DATA ROOT is missing
// pieces, e.g. after the user cleared it). Turns the bundled, vendor-stock
// Apache/PHP/MySQL binaries into a working local server:
//   1. Generate an Apache conf that points at Helm's htdocs + logs
//   2. Generate a php.ini from PHP's own php.ini-development template
//   3. Generate a minimal my.ini for MySQL
//   4. Initialize a fresh MySQL data directory (mariadb-install-db.exe)
//   5. Create htdocs with a default landing page
//
// This intentionally does NOT hand-author Apache's full module list --
// it extracts the vendor's own LoadModule lines out of the shipped
// httpd.conf and reuses them verbatim, so Helm never risks omitting a
// module the bundled Apache build actually needs.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFile } = require('child_process');
const { paths, diagnoseBinaries } = require('./config');
const { ensureVCRedist } = require('./prereqs');
const { regenerateVhostConf } = require('./vhosts');

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function extractLoadModuleLines(vendorConfText) {
  return vendorConfText
    .split(/\r?\n/)
    .filter((line) => /^\s*LoadModule\s+\S+\s+\S+/.test(line));
}

function generateApacheConf() {
  const p = paths();
  ensureDir(path.dirname(p.apache.generatedConf));
  ensureDir(p.apache.logsDir);
  ensureDir(p.htdocs);

  const vendorConfText = fs.readFileSync(p.apache.vendorConf, 'utf8');
  const loadModuleLines = extractLoadModuleLines(vendorConfText);
  const apacheServerRoot = path.dirname(path.dirname(p.apache.binary)); // .../apache

  const conf = `# Generated by Helm -- do not edit by hand, re-run setup instead.
# Module list below is copied verbatim from the bundled Apache build's own
# httpd.conf so nothing required by this specific build gets left out.

ServerRoot "${apacheServerRoot.replace(/\\/g, '/')}"
Listen ${p.apache.port}
ServerAdmin admin@localhost

${loadModuleLines.join('\n')}

TypesConfig "${apacheServerRoot.replace(/\\/g, '/')}/conf/mime.types"

ErrorLog "${p.apache.errorLog.replace(/\\/g, '/')}"
LogLevel warn
PidFile "${p.apache.pidFile.replace(/\\/g, '/')}"

# Deny-by-default for everything, matching Apache's own stock default.
# Without this, Apache walks every parent directory of a request looking
# for .htaccess files (since AllowOverride has to be explicitly disabled
# somewhere to stop that) -- which is what let it wander into and choke on
# unrelated .htaccess files elsewhere on the filesystem.
<Directory />
    AllowOverride none
    Require all denied
</Directory>

DirectoryIndex index.php index.html

# --- PHP integration ---
LoadModule php_module "${p.php.apacheModule.replace(/\\/g, '/')}"
AddHandler application/x-httpd-php .php
PHPIniDir "${path.dirname(p.php.iniFile).replace(/\\/g, '/')}"

# The default site (plain http://localhost/) is wrapped in its own explicit
# VirtualHost rather than left as top-level DocumentRoot/Directory
# directives. Apache only uses top-level DocumentRoot for requests it can't
# match to any VirtualHost -- the moment per-project vhosts.json sites exist
# (see the Include below), EVERY request on :80 gets routed through vhost
# matching, and a plain top-level DocumentRoot would silently stop being
# reachable. Defining localhost as the first, explicit VirtualHost keeps it
# working as the default regardless of how many project sites get added.
<VirtualHost *:${p.apache.port}>
    ServerName localhost

    DocumentRoot "${p.htdocs.replace(/\\/g, '/')}"
    <Directory "${p.htdocs.replace(/\\/g, '/')}">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    # phpMyAdmin lives as a sibling of htdocs (matching XAMPP's own
    # C:\\xampp\\phpMyAdmin layout, so it stays out of your actual project
    # files) -- reachable via an Alias rather than DocumentRoot, exactly how
    # XAMPP's own httpd-xampp.conf does it. Restricted to localhost: this
    # auto-logs in as root with no password, so it should never be
    # reachable from anywhere but this machine.
    Alias /phpmyadmin "${p.phpMyAdmin.dataDir.replace(/\\/g, '/')}"
    <Directory "${p.phpMyAdmin.dataDir.replace(/\\/g, '/')}">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require local
    </Directory>
</VirtualHost>

# Per-project *.local domains, managed from the Sites panel. This file
# always exists (regenerated from vhosts.json, empty-but-valid when no
# sites are configured) -- Apache refuses to start if an Include target is
# missing, so bootstrap always creates it even with zero sites.
Include "${p.vhosts.confFile.replace(/\\/g, '/')}"
`;

  fs.writeFileSync(p.apache.generatedConf, conf, 'utf8');
}

function generatePhpIni() {
  const p = paths();
  ensureDir(path.dirname(p.php.iniFile));

  let ini = fs.readFileSync(p.php.vendorIniDev, 'utf8');

  const extDir = p.php.extDir.replace(/\\/g, '/');
  ini = ini.replace(/;?\s*extension_dir\s*=.*/i, `extension_dir = "${extDir}"`);

  // Enable the extensions every one of Santos's PHP 8.2 MVC projects needs.
  const enable = ['curl', 'fileinfo', 'gd', 'mbstring', 'mysqli', 'openssl', 'pdo_mysql', 'intl'];
  for (const ext of enable) {
    const re = new RegExp(`^;\\s*extension\\s*=\\s*${ext}\\s*$`, 'mi');
    if (re.test(ini)) {
      ini = ini.replace(re, `extension=${ext}`);
    } else if (!new RegExp(`^extension\\s*=\\s*${ext}\\s*$`, 'mi').test(ini)) {
      ini += `\nextension=${ext}`;
    }
  }

  ini = ini.replace(/;?\s*upload_max_filesize\s*=.*/i, 'upload_max_filesize = 64M');
  ini = ini.replace(/;?\s*post_max_size\s*=.*/i, 'post_max_size = 64M');
  ini = ini.replace(/;?\s*max_execution_time\s*=.*/i, 'max_execution_time = 120');

  fs.writeFileSync(p.php.iniFile, ini, 'utf8');
}

function generateMyIni() {
  const p = paths();
  ensureDir(path.dirname(p.mysql.iniFile));
  ensureDir(p.mysql.dataDir);

  const basedir = p.mysql.basedir.replace(/\\/g, '/');
  const datadir = p.mysql.dataDir.replace(/\\/g, '/');

  const ini = `# Generated by Helm
[mysqld]
basedir=${basedir}
datadir=${datadir}
port=${p.mysql.port}
log-error=${p.mysql.errorLog.replace(/\\/g, '/')}

# innodb_file_per_table keeps each table in its own .ibd file, which is
# what lets Helm's "Attempt clean recovery" archive only the InnoDB system
# files (ibdata1 / ib_logfile*) without touching your actual table data.
innodb_file_per_table=1
max_allowed_packet=64M

[client]
port=${p.mysql.port}
`;

  fs.writeFileSync(p.mysql.iniFile, ini, 'utf8');
}

function generateHtdocsWelcome() {
  const p = paths();
  const indexPath = path.join(p.htdocs, 'index.php');
  if (fs.existsSync(indexPath)) return;

  const html = `<!doctype html>
<html>
<head><title>Helm</title></head>
<body style="font-family: Segoe UI, sans-serif; background:#0b1215; color:#e9ede9; padding:48px;">
  <h1 style="color:#e8c171;">Helm is running.</h1>
  <p>This is <code>htdocs\\index.php</code>. Replace it with your project, or point
  a vhost at a different folder.</p>
  <p>PHP: <?php echo phpversion(); ?></p>
  <p><a href="/phpmyadmin" style="color:#e8c171;">Open phpMyAdmin &rarr;</a></p>
</body>
</html>
`;
  fs.writeFileSync(indexPath, html, 'utf8');
}

function randomBlowfishSecret() {
  return crypto.randomBytes(32).toString('base64').slice(0, 32);
}

function setupPhpMyAdmin() {
  const p = paths();

  if (fs.existsSync(p.phpMyAdmin.configFile)) return;

  const config = `<?php
// Generated by Helm -- do not edit by hand, re-run setup instead.
declare(strict_types=1);

$cfg['blowfish_secret'] = '${randomBlowfishSecret()}';

// 'config' auth logs in automatically using the credentials below --
// this is what actually gives XAMPP-style "just open it, no login screen"
// behavior. 'cookie' (what this used to be set to) always shows a login
// form; AllowNoPassword only makes an empty password acceptable to submit
// through that form, it doesn't skip the form itself.
$cfg['Servers'][1]['auth_type'] = 'config';
$cfg['Servers'][1]['host'] = '127.0.0.1';
$cfg['Servers'][1]['port'] = ${p.mysql.port};
$cfg['Servers'][1]['user'] = 'root';
$cfg['Servers'][1]['password'] = '';
$cfg['Servers'][1]['AllowNoPassword'] = true;
$cfg['Servers'][1]['compress'] = false;

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
`;

  fs.writeFileSync(p.phpMyAdmin.configFile, config, 'utf8');
}

// Windows reports a crash caused by a missing DLL (e.g. the Visual C++
// Redistributable MariaDB needs) as one of these exit codes, surfaced
// through Node in either its signed or unsigned form depending on version.
const DLL_NOT_FOUND_CODES = new Set([3221225781, -1073741515]);

function initMysqlDataDir() {
  const p = paths();
  const systemSchema = path.join(p.mysql.dataDir, 'mysql');
  if (fs.existsSync(systemSchema)) return Promise.resolve('already initialized');

  // NOTE: MariaDB's mysqld.exe does NOT support --initialize-insecure --
  // that's a MySQL-only flag (added in MySQL 5.7). MariaDB never adopted
  // it; it ships a dedicated tool, mariadb-install-db.exe, for this exact
  // job instead. Using the wrong one produces "unknown option" and mysqld
  // aborts immediately.
  //
  // Also NOTE: unlike mysqld.exe, mariadb-install-db.exe's Windows build
  // does NOT accept --basedir -- its documented flags are --datadir,
  // --service, --password, --port, --socket, --default-user,
  // --allow-remote-root-access, --skip-networking, --innodb-page-size,
  // --silent, --verbose-bootstrap, --large-pages, --config, --help. It
  // resolves basedir itself from its own exe location, which is already
  // correct here (bin\ sits directly under the mysql basedir). Passing
  // --basedir anyway doesn't error as "unknown option" the way mysqld.exe
  // would -- it fails with "unknown variable 'basedir=...'" instead, a
  // different-enough message that it's worth calling out explicitly.
  const args = [`--datadir=${p.mysql.dataDir}`, '--verbose-bootstrap'];
  const command = `"${p.mysql.installDbBinary}" ${args.join(' ')}`;

  return new Promise((resolve, reject) => {
    execFile(
      p.mysql.installDbBinary,
      args,
      { windowsHide: true },
      (err, stdout, stderr) => {
        if (!err) return resolve(stdout);

        const details = [];
        if (stderr && stderr.trim()) details.push(`stderr: ${stderr.trim()}`);
        if (stdout && stdout.trim()) details.push(`stdout: ${stdout.trim()}`);
        if (typeof err.code === 'number') details.push(`exit code: ${err.code}`);

        if ((!stderr || !stderr.trim()) && (!stdout || !stdout.trim())) {
          if (typeof err.code === 'number' && DLL_NOT_FOUND_CODES.has(err.code)) {
            details.push(
              'This exit code is Windows\' STATUS_DLL_NOT_FOUND -- the Visual C++ Redistributable ' +
              'may not have actually installed. Try running it manually: ' +
              'https://aka.ms/vs/17/release/vc_redist.x64.exe'
            );
          } else {
            details.push(
              'mariadb-install-db.exe produced no output before exiting. Run this exact command ' +
              'directly in a terminal (not through Helm) to see the real error:\n' + command
            );
          }
        }

        reject(new Error(details.length ? details.join('\n\n') : err.message));
      }
    );
  });
}

async function runBootstrap(onProgress = () => {}) {
  const missing = diagnoseBinaries().filter((item) => !item.exists);
  if (missing.length) {
    const lines = missing.map((item) => `${item.label} (expected at ${item.path})`);
    throw new Error(
      'Bundled server binaries are missing:\n' + lines.join('\n') +
      '\nThis build of Helm was not packaged correctly -- see server-build/fetch-binaries.ps1.'
    );
  }

  onProgress('Checking Windows runtime prerequisites');
  await ensureVCRedist(onProgress);

  onProgress('Setting up Apache configuration');
  regenerateVhostConf();
  generateApacheConf();

  onProgress('Setting up PHP configuration');
  generatePhpIni();

  onProgress('Setting up MySQL configuration');
  generateMyIni();

  onProgress('Creating htdocs');
  generateHtdocsWelcome();

  onProgress('Setting up phpMyAdmin');
  setupPhpMyAdmin();

  onProgress('Initializing MySQL data directory (first run only, can take a minute)');
  await initMysqlDataDir();

  onProgress('Done');
}

module.exports = { runBootstrap, generateApacheConf, generatePhpIni, generateMyIni, initMysqlDataDir, setupPhpMyAdmin };
