// src/vhosts.js
//
// XAMPP-style per-project local domains (e.g. claimiq.local instead of just
// localhost/claimiq). Two things have to stay in sync for this to work:
//   1. A hosts file entry (127.0.0.1  claimiq.local) so Windows resolves
//      the name to this machine at all.
//   2. An Apache <VirtualHost> block so Apache knows which folder to serve
//      for that Host header once the request arrives.
//
// Both live in a single Helm-managed registry (vhosts.json) and get
// regenerated from it every time, rather than trying to surgically patch
// either file -- regenerating from one source of truth is what makes
// "remove a site" reliably clean instead of leaving stray lines behind.
//
// SAFETY: only *.local domains are ever accepted. The hosts file is a
// systemwide, security-sensitive file -- restricting to .local (never a
// real public suffix) means Helm can never be pointed at hijacking an
// actual domain, accidentally or otherwise.

const fs = require('fs');
const os = require('os');
const path = require('path');
const sudo = require('sudo-prompt');
const { paths } = require('./config');

const SUDO_OPTIONS = { name: 'Helm' };
const DOMAIN_RE = /^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)*\.local$/i;

function runElevated(cmd) {
  return new Promise((resolve, reject) => {
    sudo.exec(cmd, SUDO_OPTIONS, (err, stdout, stderr) => {
      if (err) {
        const combined = [stdout, stderr].filter((s) => s && String(s).trim()).join('\n');
        return reject(new Error(combined || err.message));
      }
      resolve(String(stdout || '').trim());
    });
  });
}

function loadRegistry() {
  const p = paths();
  try {
    return JSON.parse(fs.readFileSync(p.vhosts.registryFile, 'utf8'));
  } catch (err) {
    return [];
  }
}

function saveRegistry(list) {
  const p = paths();
  fs.mkdirSync(path.dirname(p.vhosts.registryFile), { recursive: true });
  fs.writeFileSync(p.vhosts.registryFile, JSON.stringify(list, null, 2), 'utf8');
}

function listVhosts() {
  return loadRegistry();
}

// Regenerates the Apache include file from the full registry every time --
// simpler and safer than trying to insert/remove individual blocks.
function regenerateVhostConf() {
  const p = paths();
  const list = loadRegistry();

  const blocks = list.map(({ domain, docRoot }) => `<VirtualHost *:80>
    ServerName ${domain}
    DocumentRoot "${docRoot.replace(/\\/g, '/')}"
    <Directory "${docRoot.replace(/\\/g, '/')}">
        Options Indexes FollowSymLinks
        AllowOverride All
        # Local-only by default: project folders can contain .env files,
        # vendor/, database dumps, etc. -- Require local means only this
        # machine can reach it, the same conservative default already used
        # for phpMyAdmin, rather than anything reachable on the network.
        Require local
    </Directory>
</VirtualHost>`).join('\n\n');

  const conf = `# Generated by Helm -- do not edit by hand, use the Sites panel instead.
${blocks || '# No sites configured yet.'}
`;

  fs.mkdirSync(path.dirname(p.vhosts.confFile), { recursive: true });
  fs.writeFileSync(p.vhosts.confFile, conf, 'utf8');
}

// Rewrites just the Helm-managed section of the hosts file, delimited by
// marker comments, so any other entries already in there (real projects,
// other tools) are left completely alone.
//
// This previously trusted a clean PowerShell exit code as proof the write
// succeeded -- but the script had no $ErrorActionPreference set, so
// PowerShell's default ("Continue") let a failed Set-Content print a
// non-terminating error and carry on to the final Write-Host anyway,
// reporting success while writing nothing. Now: errors are terminating,
// the read-only attribute is cleared defensively before writing (a common
// reason writes fail even when elevated), and the file is read back
// afterward to confirm the change is actually there before declaring
// success.
async function syncHostsFile() {
  const list = loadRegistry();
  const entriesPath = path.join(os.tmpdir(), `helm-vhosts-${Date.now()}.json`);
  const scriptPath = path.join(os.tmpdir(), `helm-sync-hosts-${Date.now()}.ps1`);

  fs.writeFileSync(entriesPath, JSON.stringify(list.map((v) => ({ domain: v.domain }))), 'utf8');

  const script = `param([string]$EntriesFile)
$ErrorActionPreference = "Stop"

# The hosts file is a common target for brief contention -- Windows' own
# DNS Client service reacts to changes and re-reads the file right after a
# write, which can transiently collide with whatever Helm is doing next
# (a write racing a write, or -- as seen in practice -- a read colliding
# with that same background activity and throwing "Stream was not
# readable" instead). One retry helper used for every file operation here,
# rather than separate copy-pasted retry blocks per operation, so fixing
# this can't accidentally cover only the operation that failed most
# recently and miss the next one.
function Invoke-WithRetry {
  param([scriptblock]$Action, [int]$MaxAttempts = 6)
  $attempt = 1
  $lastError = $null
  while ($attempt -le $MaxAttempts) {
    try {
      return & $Action
    } catch {
      $lastError = $_
      $attempt++
      if ($attempt -le $MaxAttempts) { Start-Sleep -Milliseconds (250 * $attempt) }
    }
  }
  throw $lastError
}

try {
  $hostsPath = "$env:WINDIR\\System32\\drivers\\etc\\hosts"
  $entries = Get-Content $EntriesFile -Raw | ConvertFrom-Json
  if ($null -eq $entries) { $entries = @() }

  $startMarker = "# ===== HELM VHOSTS START ====="
  $endMarker = "# ===== HELM VHOSTS END ====="

  # Clear the read-only attribute if set -- a common reason hosts file
  # writes silently fail even from an elevated process.
  if (Test-Path $hostsPath) {
    $item = Get-Item $hostsPath -Force
    if ($item.Attributes -band [System.IO.FileAttributes]::ReadOnly) {
      Set-ItemProperty -Path $hostsPath -Name IsReadOnly -Value $false
    }
  }

  $content = Invoke-WithRetry -Action {
    if (Test-Path $hostsPath) { Get-Content $hostsPath -Raw } else { "" }
  }
  if ($null -eq $content) { $content = "" }

  $pattern = "(?s)" + [regex]::Escape($startMarker) + ".*?" + [regex]::Escape($endMarker) + "\\r?\\n?"
  $content = [regex]::Replace($content, $pattern, "")
  $content = $content.TrimEnd()

  if ($entries.Count -gt 0) {
    $block = "$startMarker\`r\`n"
    foreach ($e in $entries) { $block += "127.0.0.1\`t$($e.domain)\`r\`n" }
    $block += "$endMarker"
    $content = $content + "\`r\`n\`r\`n" + $block + "\`r\`n"
  } else {
    $content = $content + "\`r\`n"
  }

  Invoke-WithRetry -Action {
    Set-Content -Path $hostsPath -Value $content -NoNewline -Encoding ASCII -Force
  } | Out-Null

  # Verify the write actually took effect rather than trusting a clean
  # exit code -- this read goes through the same retry helper as the
  # write, since it can hit the same transient contention.
  $verify = Invoke-WithRetry -Action { Get-Content $hostsPath -Raw }
  if ($entries.Count -gt 0 -and $verify -notmatch [regex]::Escape($startMarker)) {
    throw "Wrote to $hostsPath without error, but the Helm-managed block isn't there on re-read. Something (antivirus, Controlled Folder Access, or a file lock) is silently reverting the write."
  }

  Write-Host "Hosts file updated and verified: $($entries.Count) Helm-managed entries"
  exit 0
} catch {
  Write-Error "Hosts file sync failed: $($_.Exception.Message)"
  exit 1
}
`;

  fs.writeFileSync(scriptPath, script, 'utf8');

  try {
    return await runElevated(`powershell -ExecutionPolicy Bypass -File "${scriptPath}" -EntriesFile "${entriesPath}"`);
  } finally {
    fs.unlink(scriptPath, () => {});
    fs.unlink(entriesPath, () => {});
  }
}

async function addVhost(domain, customDocRoot) {
  const p = paths();
  const cleanDomain = String(domain || '').trim().toLowerCase();

  if (!DOMAIN_RE.test(cleanDomain)) {
    throw new Error(`"${domain}" isn't a valid .local domain. Use letters, numbers, and hyphens, ending in .local -- e.g. claimiq.local`);
  }

  const list = loadRegistry();
  if (list.some((v) => v.domain === cleanDomain)) {
    throw new Error(`${cleanDomain} is already configured.`);
  }

  let docRoot = customDocRoot;
  if (!docRoot) {
    const slug = cleanDomain.replace(/\.local$/i, '');
    docRoot = path.join(p.vhosts.sitesDir, slug);
    fs.mkdirSync(docRoot, { recursive: true });
    const indexPath = path.join(docRoot, 'index.php');
    if (!fs.existsSync(indexPath)) {
      fs.writeFileSync(indexPath, `<!doctype html>\n<html><body style="font-family:sans-serif;background:#0b1215;color:#e9ede9;padding:48px;">\n<h1>${cleanDomain}</h1>\n<p>Replace this with your project. This folder is <code>${docRoot.replace(/\\/g, '/')}</code>.</p>\n</body></html>\n`, 'utf8');
    }
  } else if (!fs.existsSync(docRoot)) {
    throw new Error(`Folder does not exist: ${docRoot}`);
  }

  list.push({ domain: cleanDomain, docRoot, createdAt: new Date().toISOString() });
  saveRegistry(list);
  regenerateVhostConf();
  await syncHostsFile();

  return { domain: cleanDomain, docRoot };
}

async function removeVhost(domain) {
  const list = loadRegistry();
  const next = list.filter((v) => v.domain !== domain);
  if (next.length === list.length) {
    throw new Error(`${domain} isn't configured.`);
  }

  saveRegistry(next);
  regenerateVhostConf();
  await syncHostsFile();
}

module.exports = { listVhosts, addVhost, removeVhost, regenerateVhostConf, syncHostsFile, DOMAIN_RE };
